services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-chess
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: chess-user
      POSTGRES_PASSWORD: Alexandre
      POSTGRES_DB: chess-api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chess-user -d chess-api"]
      interval: 5s
      timeout: 5s
      retries: 5

  chess-api:
    build: .
    container_name: chess-api
    restart: on-failure
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app         # Fixed target path
      - ./db:/app/db           # Fixed target path
      - ./scripts:/app/scripts # Fixed target path
      - ./alembic:/app/alembic # Fixed target path
    ports:
      - "8000:8000"
    environment:
      FASTAPI_WORKERS: 2
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: 